   ```yaml
   name: Build FakeServerPlayers
   on: [push]
   jobs:
     build:
       runs-on: ubuntu-latest
       steps:
       - uses: actions/checkout@v2
       - name: Set up JDK
         uses: actions/setup-java@v3
         with:
           java-version: '17'
       - name: Build
         run: ./gradlew clean build
       - uses: actions/upload-artifact@v3
         with:
           name: FakeServerPlayers-jar
           path: build/libs/FakeServerPlayers-1.0.jar
   ```
